name: INVALID_LOCKFILE_PATH_FILTERED_SENTINEL

on:
  push:
    paths:
      - only-this-path-matches/**
  pull_request:
    paths:
      - only-this-path-matches/**

jobs:
  should-not-start:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PATH_FILTERED_WORKFLOW_SHOULD_NOT_RUN"
